var pairs =
{
"creating":{"first":1}
,"first":{"popup":1}
,"popup":{"window":1,"windows":1,"paragraph":1}
,"window":{"(dita)":1,"using":1}
,"(dita)":{"previous":1}
,"previous":{"example":1}
,"example":{"explained":1}
,"explained":{"create":1}
,"create":{"popup":1,"first":1}
,"windows":{"using":1}
,"using":{"cross-references":1,"sample":1}
,"cross-references":{"glossterm":1}
,"glossterm":{"glossdef":1}
,"glossdef":{"popup":1}
,"paragraph":{"styles":1}
,"styles":{"popupend":1}
,"popupend":{"marker":1}
,"marker":{"section":1}
,"section":{"create":1}
,"sample":{"exploring":1}
,"exploring":{"epublisher":1}
,"epublisher":{"source":1}
,"source":{"documents":1}
,"documents":{"stationery":1}
}
;Search.control.loadWordPairs(pairs);
