var pairs =
{
"adding":{"functional":1}
,"functional":{"elements":1,"users":1}
,"elements":{"online":1,"add":1}
,"online":{"content":1,"features":1}
,"content":{"(dita)":1,"elements":1,"aesthetically":1,"enabling":1,"involves":1}
,"(dita)":{"generate":1}
,"generate":{"online":1}
,"add":{"content":1,"online":1}
,"aesthetically":{"appealing":1}
,"appealing":{"functional":1}
,"users":{"example":1}
,"example":{"using":1}
,"using":{"webworks":1}
,"webworks":{"help":1}
,"help":{"microsoft":1,"output":1,"topics":1}
,"microsoft":{"html":1}
,"html":{"help":1}
,"output":{"format":1}
,"format":{"add":1}
,"features":{"popup":1,"online":1,"following":1}
,"popup":{"windows":1}
,"windows":{"expand\u002Fcollapse":1,"(dita)":1}
,"expand\u002Fcollapse":{"sections":1}
,"sections":{"related":1,"explain":1,"(dita)":1}
,"related":{"topics":1}
,"topics":{"links":1,"(dita)":1}
,"links":{"enhance":1,"(dita)":1}
,"enhance":{"usability":1}
,"usability":{"online":1}
,"enabling":{"features":1}
,"involves":{"configuring":1}
,"configuring":{"source":1}
,"source":{"documents":1}
,"documents":{"appropriate":1,"stationery":1}
,"appropriate":{"paragraph":1}
,"paragraph":{"character":1}
,"character":{"styles":1}
,"styles":{"marker":1}
,"marker":{"types":1,"type":1}
,"types":{"epublisher":1,"sample":1}
,"epublisher":{"uses":1,"source":1}
,"uses":{"style":1}
,"style":{"marker":1}
,"type":{"information":1}
,"information":{"implement":1}
,"implement":{"online":1,"following":1}
,"following":{"sections":1,"online":1}
,"explain":{"paragraph":1}
,"sample":{"exploring":1,"source":1}
,"exploring":{"epublisher":1}
,"stationery":{"implement":1,"(dita)":1}
,"context-sensitive":{"help":1}
,"parent":{"topic":1}
}
;Search.control.loadWordPairs(pairs);
