var pairs =
{
"dita":{"styles":1,"files":1,"source":1}
,"styles":{"quick":1,"derived":1,"used":1,"marker":1,"(dita)":1}
,"quick":{"reference":1}
,"epublisher":{"dita":1,"style":1}
,"derived":{"structure":1}
,"structure":{"dita":1}
,"files":{"element":1}
,"element":{"hierarchy":1}
,"hierarchy":{"specialization":1}
,"specialization":{"play":1}
,"play":{"role":1}
,"role":{"deriving":1}
,"deriving":{"epublisher":1}
,"style":{"given":1}
,"given":{"fragment":1}
,"fragment":{"dita":1}
,"source":{"content":1}
,"content":{"following":1}
,"following":{"information":1}
,"information":{"provides":1,"section":1}
,"provides":{"definitions":1}
,"definitions":{"styles":1}
,"used":{"within":1}
,"within":{"project":1}
,"project":{"information":1}
,"section":{"learn":1}
,"learn":{"different":1}
,"different":{"paragraph":1}
,"paragraph":{"character":1,"styles":1}
,"character":{"styles":1}
,"marker":{"types":1}
,"types":{"used":1,"(dita)":1}
}
;Search.control.loadWordPairs(pairs);
