var pairs =
{
"sample":{"exploring":1,"source":1}
,"exploring":{"epublisher":1}
,"epublisher":{"stationery":1,"pro":1,"express":1}
,"stationery":{"(dita)":1,"created":1,"designer":1,"design":1}
,"(dita)":{"sample":1}
,"created":{"stationery":1}
,"designer":{"using":1,"contains":1}
,"using":{"epublisher":1}
,"pro":{"stationery":1}
,"design":{"project":1}
,"project":{"stationery":1,"generate":1}
,"contains":{"style":1}
,"style":{"formatting":1}
,"formatting":{"information":1}
,"information":{"settings":1}
,"settings":{"serves":1,"rules":1}
,"serves":{"reusable":1}
,"reusable":{"settings":1}
,"rules":{"quickly":1}
,"quickly":{"easily":1}
,"easily":{"create":1}
,"create":{"new":1}
,"new":{"epublisher":1}
,"express":{"project":1}
,"generate":{"output":1}
,"parent":{"topic":1}
,"source":{"documents":1}
,"documents":{"stationery":1}
}
;Search.control.loadWordPairs(pairs);
