var pairs =
{
"sample":{"exploring":1,"dita":1,"paragraph":1,"character":1,"project":1,"source":1}
,"exploring":{"epublisher":1}
,"epublisher":{"source":1,"capabilities":1,"evaluation":1,"section":1,"writer":1,"help":1,"express":1}
,"source":{"documents":1}
,"documents":{"(dita)":1,"contain":1,"configuration":1,"request":1,"stationery":1,"content":1,"please":1,"information":1}
,"(dita)":{"sample":1}
,"dita":{"exploring":1,"source":1,"configurations":1,"configuration":1}
,"contain":{"paragraph":1,"sample":1}
,"paragraph":{"character":1,"styles":1}
,"character":{"styles":1}
,"styles":{"marker":1,"heading":1,"sample":1,"bold":1,"using":1}
,"marker":{"types":1}
,"types":{"explore":1,"generate":1}
,"explore":{"epublisher":1}
,"capabilities":{"example":1}
,"example":{"sample":1}
,"configuration":{"contain":1,"help":1}
,"heading":{"heading":1,"title":1}
,"title":{"body":1}
,"body":{"paragraph":1}
,"bold":{"command":1}
,"command":{"common":1}
,"common":{"dita":1}
,"configurations":{"sample":1}
,"request":{"epublisher":1}
,"evaluation":{"following":1,"guide":1}
,"following":{"ways":1}
,"follow":{"instructions":1}
,"instructions":{"exploring":1,"work":1}
,"section":{"epublisher":1}
,"guide":{"epublisher":1}
,"writer":{"guide":1}
,"help":{"sample":1,"topics":1,"topic":1,"parent":1}
,"stationery":{"create":1,"exploring":1,"(dita)":1}
,"create":{"sample":1}
,"project":{"epublisher":1,"generate":1}
,"express":{"creating":1}
,"creating":{"sample":1}
,"generate":{"output":1,"result":1}
,"output":{"generated":1,"displays":1,"implement":1,"information":1}
,"generated":{"output":1}
,"displays":{"customize":1}
,"customize":{"output":1}
,"implement":{"online":1}
,"online":{"features":1}
,"features":{"popup":1}
,"popup":{"windows":1}
,"windows":{"expand\u002Fcollapse":1}
,"expand\u002Fcollapse":{"sections":1}
,"sections":{"related":1}
,"related":{"topics":1}
,"topics":{"links":1,"replace":1}
,"links":{"context-sensitive":1}
,"context-sensitive":{"help":1}
,"replace":{"existing":1}
,"existing":{"content":1}
,"content":{"sample":1,"configure":1}
,"configure":{"paragraph":1}
,"result":{"review":1}
,"review":{"output":1}
,"information":{"configuring":1,"step-by-step":1}
,"configuring":{"styles":1}
,"using":{"dita":1}
,"please":{"wiki":1}
,"wiki":{"topic":1}
,"topic":{"dita":1,"preparing":1}
,"preparing":{"dita":1}
,"step-by-step":{"instructions":1}
,"work":{"sample":1}
,"parent":{"topic":1}
}
;Search.control.loadWordPairs(pairs);
