var pairs =
{
"creating":{"first":1}
,"first":{"context-sensitive":1}
,"context-sensitive":{"help":1}
,"help":{"topic":1,"topics":1}
,"topic":{"(dita)":1,"using":1}
,"(dita)":{"previous":1}
,"previous":{"section":1}
,"section":{"explains":1,"create":1}
,"explains":{"create":1}
,"create":{"context-sensitive":1,"first":1}
,"topics":{"using":1}
,"using":{"dita":1,"exploring":1}
,"dita":{"<othermeta>":1}
,"<othermeta>":{"elements":1}
,"elements":{"section":1}
,"exploring":{"epublisher":1}
,"epublisher":{"source":1}
,"source":{"documents":1}
,"documents":{"stationery":1}
}
;Search.control.loadWordPairs(pairs);
