var pairs =
{
"creating":{"popup":1}
,"popup":{"windows":1,"window":1,"components":1,"content":1,"paragraph":1}
,"windows":{"(dita)":1,"display":1}
,"online":{"content":1,"help":1}
,"content":{"help":1,"link":1,"popup":1}
,"help":{"systems":1,"popup":1}
,"systems":{"commonly":1}
,"commonly":{"popup":1,"used":1}
,"display":{"definitions":1}
,"definitions":{"terms":1,"exploring-epublisher.ditamap":1}
,"terms":{"writers":1,"glossary":1,"epublisher":1}
,"writers":{"choose":1}
,"choose":{"define":1}
,"define":{"commonly":1,"boundaries":1}
,"used":{"terms":1}
,"glossary":{"online":1,"terms":1}
,"window":{"displayed":1,"example":1}
,"displayed":{"user":1,"popup":1}
,"user":{"hovers":1}
,"hovers":{"clicks":1}
,"clicks":{"glossary":1}
,"epublisher":{"allows":1}
,"allows":{"create":1}
,"create":{"popups":1}
,"popups":{"text":1}
,"text":{"source":1,"displayed":1}
,"source":{"documents":1}
,"enabling":{"behavior":1}
,"behavior":{"involves":1}
,"involves":{"setting":1}
,"setting":{"necessary":1}
,"necessary":{"popup":1}
,"components":{"source":1}
,"documents":{"based":1}
,"based":{"settings":1}
,"settings":{"stationery":1}
,"stationery":{"designer":1,"hover":1}
,"designer":{"configured":1,"defined":1}
,"configured":{"stationery":1}
,"hover":{"click":1}
,"click":{"action":1}
,"action":{"results":1}
,"results":{"following":1}
,"following":{"behaviors":1,"procedure":1}
,"behaviors":{"link":1}
,"link":{"takes":1,"displays":1,"definitions":1}
,"takes":{"users":1}
,"users":{"location":1}
,"location":{"popup":1}
,"displays":{"content":1}
,"example":{"glossterm":1}
,"glossterm":{"glossdef":1}
,"glossdef":{"links":1,"paragraph":1}
,"links":{"following":1}
,"procedure":{"dita":1}
,"dita":{"xref":1}
,"xref":{"elements":1}
,"elements":{"link":1}
,"exploring-epublisher.ditamap":{"file":1}
,"file":{"stationery":1}
,"defined":{"glossterm":1}
,"paragraph":{"styles":1}
,"styles":{"popup":1,"define":1}
,"boundaries":{"text":1}
}
;Search.control.loadWordPairs(pairs);
