var pairs =
{
"creating":{"related":1}
,"related":{"topics":1,"topic":1}
,"topics":{"links":1,"within":1,"writers":1,"button":1,"topic":1,"applied":1}
,"links":{"(dita)":1,"cross-references":1,"users":1,"display":1,"applying":1}
,"cross-references":{"topics":1,"want":1}
,"within":{"online":1}
,"online":{"content":1}
,"content":{"related":1}
,"topic":{"links":1,"currently":1,"source":1}
,"users":{"topics":1,"useful":1,"click":1}
,"writers":{"believe":1}
,"believe":{"provide":1}
,"provide":{"users":1}
,"useful":{"information":1}
,"information":{"topic":1}
,"currently":{"viewing":1}
,"viewing":{"based":1}
,"based":{"output":1}
,"output":{"format":1,"related":1,"user":1,"sample":1,"create":1,"list":1}
,"format":{"settings":1}
,"settings":{"specified":1}
,"specified":{"stationery":1}
,"stationery":{"related":1,"designer":1,"configured":1}
,"display":{"users":1,"either":1,"related":1,"click":1}
,"click":{"related":1}
,"button":{"generated":1}
,"generated":{"output":1}
,"either":{"text":1}
,"text":{"generated":1}
,"user":{"clicks":1}
,"clicks":{"related":1}
,"sample":{"exploring":1}
,"exploring":{"epublisher":1}
,"epublisher":{"stationery":1}
,"designer":{"stationery":1}
,"configured":{"related":1}
,"create":{"related":1}
,"applying":{"relatedtopic":1}
,"relatedtopic":{"paragraph":1}
,"paragraph":{"style":1}
,"style":{"list":1,"automatically":1}
,"list":{"cross-references":1,"topics":1}
,"want":{"display":1}
,"source":{"documents":1}
,"documents":{"generated":1}
,"applied":{"relatedtopic":1}
,"automatically":{"display":1}
}
;Search.control.loadWordPairs(pairs);
