var pairs =
{
"create":{"first":1,"tasks":1}
,"first":{"expand\u002Fcollapse":1}
,"expand\u002Fcollapse":{"section":1}
,"tasks":{"using":1}
,"using":{"dita":1,"version":1}
,"dita":{"<steps>":1}
,"<steps>":{"element":1}
,"element":{"child":1}
,"child":{"elements":1}
,"configure":{"epublisher":1}
,"epublisher":{"stationery":1}
,"stationery":{"customizing":1,"guide":1,"specifies":1}
,"customizing":{"default.wwconfig":1}
,"default.wwconfig":{"file":1}
,"file":{"using":1}
,"version":{"stationery":1}
,"guide":{"sure":1}
,"sure":{"epublisher":1}
,"specifies":{"dropdown":1}
,"dropdown":{"start":1,"break":1}
,"start":{"closed":1}
,"closed":{"behavior":1}
,"behavior":{"task":1,"steps":1}
,"task":{"title":1}
,"title":{"paragraph":1}
,"paragraph":{"style":1}
,"style":{"sure":1}
,"break":{"behavior":1}
,"steps":{"close":1}
,"close":{"paragraph":1}
,"generate":{"output":1}
,"output":{"verify":1}
,"verify":{"expand\u002Fcollapse":1}
,"section":{"behaves":1}
,"behaves":{"demonstrated":1}
,"demonstrated":{"example":1}
}
;Search.control.loadWordPairs(pairs);
