var pairs =
{
"related":{"topics":1}
,"topics":{"links":1}
,"links":{"(dita)":1,"epublisher":1,"topic":1}
,"(dita)":{"section":1}
,"section":{"explains":1,"allows":1}
,"explains":{"create":1}
,"create":{"related":1}
,"epublisher":{"section":1,"source":1}
,"allows":{"create":1}
,"topic":{"using":1}
,"using":{"sample":1}
,"sample":{"exploring":1}
,"exploring":{"epublisher":1}
,"source":{"documents":1}
,"documents":{"stationery":1}
}
;Search.control.loadWordPairs(pairs);
