var pairs =
{
"creating":{"expand\u002Fcollapse":1}
,"expand\u002Fcollapse":{"sections":1}
,"sections":{"(dita)":1,"links":1,"accomplished":1}
,"links":{"generated":1}
,"generated":{"output":1}
,"output":{"users":1}
,"users":{"click":1}
,"click":{"expand":1,"arrow":1}
,"expand":{"collapse":1}
,"collapse":{"content":1}
,"content":{"creating":1}
,"accomplished":{"setting":1}
,"setting":{"boundaries":1}
,"boundaries":{"expansion":1}
,"expansion":{"section":1}
,"section":{"epublisher":1,"steps":1}
,"epublisher":{"paragraph":1,"steps":1,"task":1,"design":1}
,"paragraph":{"styles":1}
,"styles":{"example":1,"task\u002Ftitle":1}
,"example":{"<steps>":1}
,"<steps>":{"element":1}
,"element":{"configured":1}
,"configured":{"appear":1}
,"appear":{"within":1}
,"within":{"epublisher":1}
,"steps":{"open":1,"close":1,"procedure":1}
,"open":{"steps":1}
,"close":{"paragraph":1,"style":1}
,"task\u002Ftitle":{"element":1}
,"task":{"title":1}
,"title":{"designer":1,"style":1}
,"designer":{"stationery":1}
,"stationery":{"used":1}
,"used":{"epublisher":1,"mark":1}
,"design":{"project":1}
,"project":{"specify":1}
,"specify":{"task":1}
,"style":{"mark":1,"used":1}
,"mark":{"beginning":1,"end":1}
,"beginning":{"dropdown":1}
,"dropdown":{"section":1}
,"end":{"dropdown":1}
,"arrow":{"display":1}
,"display":{"steps":1}
,"procedure":{"below":1}
}
;Search.control.loadWordPairs(pairs);
