var pairs =
{
"paragraph":{"styles":1,"style":1}
,"styles":{"(dita)":1,"apply":1,"want":1,"quick":1,"allow":1,"provide":1,"used":1}
,"apply":{"entire":1,"certain":1,"glossdef":1,"greater":1,"style":1}
,"entire":{"paragraphs":1}
,"paragraphs":{"text":1}
,"text":{"paragraph":1,"part":1,"want":1,"appear":1}
,"want":{"apply":1,"display":1,"indent":1}
,"certain":{"formatting":1}
,"formatting":{"particular":1}
,"particular":{"section":1}
,"section":{"content":1,"marker":1}
,"bullet":{"bullet":1,"dropdownend":1,"styles":1}
,"heading1":{"heading":1}
,"heading":{"heading":1,"indent1":1,"styles":1,"style":1}
,"indent1":{"indent2":1,"want":1}
,"number":{"number":1,"relatedlinks":1,"styles":1,"style":1}
,"parent":{"topic":1}
,"dita":{"styles":1}
,"quick":{"reference":1}
,"body":{"content":1,"document":1,"paragraph":1,"style":1}
,"content":{"serves":1,"want":1,"glossterm":1,"level":1,"two":1,"following":1}
,"serves":{"body":1}
,"document":{"uses":1,"style":1}
,"uses":{"body":1,"autonumbering":1}
,"style":{"example":1,"bullet2":1,"provides":1,"applied":1,"text":1,"always":1,"differs":1,"indent1":1,"indent2":1,"content":1,"creates":1,"list":1,"allows":1,"uses":1}
,"example":{"text":1}
,"part":{"table":1}
,"table":{"numbered":1}
,"numbered":{"bulleted":1}
,"bulleted":{"list":1}
,"list":{"body":1,"number1":1,"cross-references":1}
,"allow":{"create":1}
,"create":{"unordered":1,"ordered":1}
,"unordered":{"lists":1}
,"lists":{"bullet":1,"first":1}
,"provide":{"level":1}
,"level":{"indentation":1,"body":1}
,"indentation":{"matches":1,"body":1}
,"matches":{"exactly":1}
,"exactly":{"body":1}
,"bullet2":{"style":1}
,"provides":{"level":1}
,"dropdownend":{"dropdownend":1,"marker":1}
,"marker":{"inserted":1,"indicates":1}
,"inserted":{"end":1}
,"end":{"text":1,"content":1}
,"display":{"expand\u002Fcollapse":1,"links":1}
,"expand\u002Fcollapse":{"section":1}
,"indicates":{"end":1}
,"glossdef":{"glossdef":1,"style":1}
,"applied":{"glossary":1}
,"glossary":{"definition":1,"terms":1,"term":1}
,"definition":{"glossary":1}
,"terms":{"apply":1}
,"appear":{"popup":1}
,"popup":{"window":1}
,"glossterm":{"glossterm":1,"style":1}
,"term":{"appear":1}
,"window":{"content":1}
,"always":{"precede":1}
,"precede":{"glossdef":1}
,"used":{"label":1,"want":1}
,"label":{"titles":1}
,"titles":{"major":1}
,"major":{"sections":1}
,"sections":{"source":1}
,"source":{"documents":1}
,"documents":{"heading":1}
,"differs":{"font":1}
,"font":{"size":1,"weight":1}
,"size":{"font":1}
,"indent2":{"indent":1,"want":1}
,"indent":{"styles":1,"content":1}
,"greater":{"level":1}
,"two":{"levels":1}
,"levels":{"body":1}
,"ordered":{"lists":1}
,"first":{"item":1}
,"item":{"list":1,"number":1}
,"number1":{"style":1}
,"following":{"first":1}
,"relatedlinks":{"relatedlinks":1,"style":1}
,"creates":{"related":1}
,"related":{"topics":1}
,"topics":{"links":1}
,"links":{"generated":1}
,"generated":{"output":1}
,"output":{"apply":1}
,"cross-references":{"want":1}
,"title":{"chapter":1,"paragraph":1}
,"chapter":{"title":1,"numbers":1}
,"allows":{"identify":1}
,"identify":{"new":1}
,"new":{"chapters":1}
,"chapters":{"document":1}
,"autonumbering":{"append":1}
,"append":{"chapter":1}
,"numbers":{"headings":1}
}
;Search.control.loadWordPairs(pairs);
