var pairs =
{
"create":{"first":1}
,"first":{"popup":1}
,"popup":{"window":1}
,"window":{"sample":1,"created":1}
,"sample":{"stationery":1,"exploring":1}
,"stationery":{"includes":1,"exploring":1}
,"includes":{"custom":1}
,"custom":{"default.wwconfig":1}
,"default.wwconfig":{"configuration":1}
,"configuration":{"creates":1,"help":1}
,"creates":{"dedicated":1}
,"dedicated":{"paragraph":1}
,"paragraph":{"styles":1}
,"styles":{"glossterm":1,"using":1}
,"glossterm":{"glossdef":1}
,"glossdef":{"paragraph":1}
,"generate":{"output":1}
,"output":{"verify":1}
,"verify":{"popup":1}
,"created":{"section":1}
,"section":{"displays":1,"epublisher":1}
,"displays":{"correctly":1}
,"correctly":{"information":1}
,"information":{"configuring":1,"step-by-step":1}
,"configuring":{"styles":1}
,"using":{"dita":1}
,"dita":{"source":1,"configuration":1}
,"source":{"documents":1}
,"documents":{"please":1,"information":1,"stationery":1}
,"please":{"wiki":1}
,"wiki":{"topic":1}
,"topic":{"dita":1,"preparing":1}
,"help":{"topic":1}
,"preparing":{"dita":1}
,"step-by-step":{"instructions":1}
,"instructions":{"work":1}
,"work":{"sample":1}
,"exploring":{"epublisher":1}
,"epublisher":{"source":1,"section":1,"evaluation":1,"writer":1,"help":1}
,"evaluation":{"guide":1}
,"guide":{"epublisher":1}
,"writer":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
