var pairs =
{
"character":{"styles":1}
,"styles":{"(dita)":1,"allow":1,"need":1,"want":1,"quick":1}
,"allow":{"override":1}
,"override":{"paragraph":1}
,"paragraph":{"styles":1,"without":1}
,"need":{"change":1}
,"change":{"style":1}
,"style":{"attributes":1,"allows":1,"applies":1,"applied":1}
,"attributes":{"for4":1}
,"for4":{"small":1}
,"small":{"amount":1}
,"amount":{"text":1}
,"text":{"example":1,"appear":1,"allows":1,"text":1,"sub":1,"super":1}
,"example":{"character":1}
,"want":{"underline":1}
,"underline":{"specific":1,"text":1,"underline":1,"style":1,"underneath":1}
,"specific":{"word":1}
,"word":{"paragraph":1}
,"without":{"underlining":1}
,"underlining":{"entire":1}
,"entire":{"paragraph":1}
,"parent":{"topic":1}
,"dita":{"styles":1}
,"quick":{"reference":1}
,"bold":{"bold":1,"style":1}
,"allows":{"stress":1,"apply":1,"italicize":1,"clearly":1,"add":1}
,"stress":{"certain":1}
,"certain":{"words":1}
,"words":{"phrases":1}
,"phrases":{"throughout":1}
,"throughout":{"content":1}
,"code":{"code":1,"style":1,"content":1}
,"apply":{"monospace":1,"subscript":1,"superscript":1}
,"monospace":{"font":1}
,"font":{"text":1,"underline":1}
,"appear":{"code":1}
,"emphasis":{"emphasis":1,"style":1}
,"italicize":{"certain":1}
,"hyperlink":{"hyperlink":1,"style":1}
,"applies":{"blue":1}
,"blue":{"font":1}
,"clearly":{"display":1}
,"display":{"url":1}
,"url":{"addresses":1}
,"addresses":{"links":1}
,"links":{"clickable":1}
,"clickable":{"items":1}
,"sub":{"sub":1,"style":1}
,"subscript":{"font":1}
,"applied":{"displays":1}
,"displays":{"below":1,"above":1}
,"below":{"baseline":1}
,"baseline":{"normal":1}
,"normal":{"text":1}
,"super":{"super":1,"style":1}
,"superscript":{"font":1}
,"above":{"baseline":1}
,"add":{"underline":1}
,"underneath":{"text":1}
}
;Search.control.loadWordPairs(pairs);
