var pairs =
{
"create":{"first":1}
,"first":{"context-sensitive":1}
,"context-sensitive":{"help":1}
,"help":{"topic":1}
,"topic":{"dita":1,"context-sensitive-help-topics.xml":1}
,"dita":{"topic":1}
,"context-sensitive-help-topics.xml":{"add":1}
,"add":{"<prolog>\u002F<metadata>\u002F<othermeta>":1}
,"<prolog>\u002F<metadata>\u002F<othermeta>":{"element":1}
,"element":{"name":1,"topicalias":1,"idh_creatingyourfirstcontextsensitivehelptopicdita":1}
,"name":{"attribute":1}
,"attribute":{"<othermeta>":1}
,"<othermeta>":{"element":1}
,"topicalias":{"content":1}
,"content":{"attribute":1}
,"idh_creatingyourfirstcontextsensitivehelptopicdita":{"save":1}
,"save":{"dita":1}
,"generate":{"output":1}
,"double-click":{"topics":1}
,"topics":{"report":1}
,"report":{"icon":1}
,"icon":{"output":1}
,"output":{"explorer":1}
,"explorer":{"verify":1}
,"verify":{"appears":1}
}
;Search.control.loadWordPairs(pairs);
