var pairs =
{
"marker":{"types":1,"inserted":1,"text":1,"indicates":1}
,"types":{"(dita)":1,"allow":1}
,"allow":{"embed":1}
,"embed":{"information":1}
,"information":{"source":1}
,"source":{"documents":1}
,"documents":{"add":1}
,"add":{"functional":1}
,"functional":{"elements":1}
,"elements":{"generated":1}
,"generated":{"output":1}
,"output":{"example":1,"apply":1,"filenames":1,"specify":1}
,"example":{"markers":1}
,"markers":{"create":1}
,"create":{"popup":1}
,"popup":{"windows":1,"window":1}
,"windows":{"context-sensitive":1}
,"context-sensitive":{"help":1}
,"help":{"topics":1,"topic":1}
,"parent":{"topic":1}
,"dita":{"styles":1}
,"styles":{"quick":1}
,"quick":{"reference":1}
,"expandcollapse":{"expandcollapse":1,"style":1}
,"style":{"creates":1,"text":1}
,"creates":{"links":1}
,"links":{"display":1}
,"display":{"hide":1,"popup":1}
,"hide":{"content":1}
,"content":{"expand\u002Fcollapse":1}
,"expand\u002Fcollapse":{"section":1}
,"section":{"generated":1}
,"apply":{"style":1}
,"text":{"want":1,"marker":1,"display":1}
,"want":{"serve":1,"specify":1,"display":1,"context-sensitive":1}
,"serve":{"link":1}
,"link":{"expand\u002Fcollapse":1}
,"filename":{"filename":1,"marker":1}
,"inserted":{"want":1,"text":1,"topic":1}
,"specify":{"output":1,"desired":1,"topic":1}
,"filenames":{"epublisher":1}
,"epublisher":{"generated":1}
,"desired":{"name":1}
,"name":{"file":1}
,"file":{"marker":1}
,"popupend":{"popupend":1,"marker":1}
,"window":{"marker":1}
,"indicates":{"end":1}
,"end":{"text":1}
,"topicalias":{"topicalias":1,"marker":1}
,"topic":{"want":1,"specify":1,"wish":1,"marker":1}
,"wish":{"assign":1}
,"assign":{"topic":1}
}
;Search.control.loadWordPairs(pairs);
