var pairs =
{
"sample":{"source":1,"exploring":1}
,"source":{"documents":1}
,"documents":{"stationery":1,"(dita)":1}
,"stationery":{"(dita)":1,"designer":1,"saved":1,"define":1,"ensures":1,"provided":1}
,"epublisher":{"gives":1,"workflow":1,"source":1,"stationery":1}
,"gives":{"writers":1}
,"writers":{"streamlined":1,"focus":1,"generate":1}
,"streamlined":{"efficient":1}
,"efficient":{"workflow":1}
,"workflow":{"clearly":1,"writers":1,"using":1}
,"clearly":{"establishes":1}
,"establishes":{"role":1}
,"role":{"person":1}
,"person":{"writing":1}
,"writing":{"group":1,"teams":1}
,"group":{"within":1}
,"within":{"epublisher":1}
,"focus":{"creating":1}
,"creating":{"content":1,"using":1}
,"content":{"stationery":1,"look":1,"users":1,"(dita)":1}
,"designer":{"specifies":1}
,"specifies":{"content":1}
,"look":{"writers":1}
,"generate":{"output":1}
,"output":{"stationery":1,"generated":1,"formats":1,"learn":1}
,"saved":{"stationery":1}
,"using":{"stationery":1,"items":1}
,"define":{"appearance":1}
,"appearance":{"given":1}
,"given":{"deliverable":1}
,"deliverable":{"writing":1}
,"teams":{"focus":1}
,"users":{"need":1,"variety":1}
,"need":{"using":1}
,"ensures":{"output":1}
,"generated":{"appropriately":1}
,"appropriately":{"users":1}
,"variety":{"output":1}
,"formats":{"sample":1}
,"exploring":{"epublisher":1}
,"provided":{"order":1}
,"order":{"demonstrate":1}
,"demonstrate":{"efficiency":1}
,"efficiency":{"ease":1}
,"ease":{"epublisher":1}
,"items":{"allows":1}
,"allows":{"quickly":1}
,"quickly":{"easily":1}
,"easily":{"generate":1}
,"learn":{"epublisher\u2019s":1}
,"epublisher\u2019s":{"capabilities":1}
,"capabilities":{"sample":1}
,"(dita)":{"sample":1}
,"adding":{"functional":1}
,"functional":{"elements":1}
,"elements":{"online":1}
,"online":{"content":1}
}
;Search.control.loadWordPairs(pairs);
