var pairs =
{
"create":{"popup":1,"xref":1}
,"popup":{"window":1,"link":1,"content":1,"windows":1}
,"xref":{"element":1}
,"element":{"content":1}
,"content":{"serve":1,"want":1,"following":1}
,"serve":{"popup":1}
,"link":{"element":1}
,"want":{"display":1}
,"display":{"popup":1,"microsoft":1}
,"window":{"epublisher":1}
,"epublisher":{"stationery":1}
,"stationery":{"glossterm":1}
,"glossterm":{"glossdef":1}
,"glossdef":{"paragraph":1}
,"paragraph":{"styles":1}
,"styles":{"configured":1}
,"configured":{"display":1}
,"following":{"figure":1}
,"figure":{"shows":1}
,"shows":{"example":1}
,"example":{"popup":1}
,"windows":{"display":1}
,"microsoft":{"html":1}
,"html":{"help":1}
}
;Search.control.loadWordPairs(pairs);
