var pairs =
{
"create":{"first":1,"<related-links>":1}
,"first":{"related":1,"popup":1,"expand\u002Fcollapse":1}
,"related":{"topics":1,"concepts":1}
,"topics":{"list":1,"button":1,"links":1}
,"<related-links>":{"section":1}
,"section":{"dita":1}
,"dita":{"source":1}
,"source":{"content":1}
,"configure":{"epublisher":1}
,"epublisher":{"stationery":1}
,"stationery":{"customizing":1,"guide":1}
,"customizing":{"default.wwconfig":1}
,"default.wwconfig":{"file":1}
,"file":{"using":1}
,"using":{"version":1}
,"version":{"stationery":1}
,"guide":{"generate":1}
,"generate":{"output":1}
,"verify":{"topic":1,"click":1}
,"topic":{"displays":1,"generated":1}
,"displays":{"related":1,"contains":1}
,"button":{"bottom":1,"list":1}
,"bottom":{"topic":1}
,"generated":{"output":1}
,"click":{"related":1}
,"list":{"related":1}
,"links":{"displays":1,"listed":1}
,"contains":{"links":1}
,"listed":{"end":1}
,"end":{"section":1}
,"creating":{"first":1}
,"popup":{"window":1}
,"expand\u002Fcollapse":{"section":1}
}
;Search.control.loadWordPairs(pairs);
