var pairs =
{
"creating":{"context-sensitive":1,"topicalias":1}
,"context-sensitive":{"help":1,"behavior":1}
,"help":{"topics":1,"answer":1,"allowing":1,"button":1,"topic":1}
,"topics":{"(dita)":1,"provide":1,"topicalias":1}
,"provide":{"users":1,"information":1}
,"users":{"immediate":1,"click":1}
,"immediate":{"assistance":1}
,"assistance":{"without":1}
,"without":{"requiring":1}
,"requiring":{"leave":1}
,"leave":{"context":1}
,"context":{"working":1,"applications":1}
,"working":{"help":1}
,"answer":{"questions":1}
,"questions":{"provide":1}
,"information":{"particular":1}
,"particular":{"object":1}
,"object":{"context":1}
,"applications":{"support":1,"topic":1}
,"support":{"context-sensitive":1}
,"allowing":{"user":1}
,"user":{"click":1,"clicks":1,"viewing":1}
,"click":{"help":1}
,"button":{"application":1,"context-sensitive":1}
,"application":{"window":1,"following":1}
,"window":{"user":1,"displays":1,"dita":1}
,"clicks":{"help":1}
,"topic":{"related":1,"associated":1,"ids":1,"value":1,"determine":1,"display":1,"create":1}
,"related":{"application":1}
,"viewing":{"displays":1}
,"displays":{"example":1}
,"example":{"within":1}
,"within":{"application":1}
,"following":{"window":1}
,"associated":{"window":1}
,"epublisher":{"allows":1,"design":1}
,"allows":{"create":1}
,"create":{"context-sensitive":1,"<othermeta>":1}
,"topicalias":{"markers":1,"marker":1,"content":1}
,"markers":{"topic":1,"may":1}
,"ids":{"dita":1}
,"dita":{"markers":1,"topic":1}
,"may":{"customized":1}
,"customized":{"based":1}
,"based":{"element":1}
,"element":{"<othermeta>":1,"name":1}
,"<othermeta>":{"creating":1,"specify":1,"element":1}
,"marker":{"<othermeta>":1,"type":1}
,"specify":{"topic":1}
,"value":{"content":1}
,"content":{"attribute":1}
,"attribute":{"applications":1,"defined":1,"idh_creatingcontextsensitivehelptopicsdita":1}
,"determine":{"topic":1}
,"display":{"users":1}
,"name":{"attribute":1}
,"defined":{"topicalias":1}
,"idh_creatingcontextsensitivehelptopicsdita":{"designer":1}
,"designer":{"stationery":1}
,"stationery":{"already":1}
,"already":{"assigned":1}
,"assigned":{"appropriate":1}
,"appropriate":{"context-sensitive":1}
,"behavior":{"topicalias":1}
,"type":{"epublisher":1}
,"design":{"project":1}
}
;Search.control.loadWordPairs(pairs);
