var pairs =
{
"create":{"expand\u002Fcollapse":1,"content":1}
,"expand\u002Fcollapse":{"sections":1}
,"content":{"serve":1,"<title>":1,"expanded":1}
,"serve":{"link":1}
,"link":{"users":1}
,"users":{"click":1}
,"click":{"expand":1}
,"expand":{"collapse":1}
,"collapse":{"content":1}
,"<title>":{"element":1}
,"element":{"dita":1,"specify":1}
,"dita":{"<task>":1}
,"<task>":{"sure":1}
,"sure":{"stationery":1}
,"stationery":{"configuration":1}
,"configuration":{"uses":1}
,"uses":{"container":1}
,"container":{"boundaries":1}
,"boundaries":{"marked":1}
,"marked":{"<steps>":1}
,"<steps>":{"element":1}
,"specify":{"end":1}
,"end":{"content":1}
,"expanded":{"collapsed":1}
}
;Search.control.loadWordPairs(pairs);
