var pairs =
{
"source":{"document":1}
,"lorem":{"ipsum":1,"porttitor":1}
,"ipsum":{"dolor":1}
,"dolor":{"sit":1}
,"sit":{"amet":1}
,"amet":{"consectetuer":1,"commodo":1}
,"consectetuer":{"adipiscing":1}
,"adipiscing":{"elit":1}
,"elit":{"maecenas":1}
,"maecenas":{"porttitor":1}
,"porttitor":{"congue":1,"donec":1}
,"congue":{"massa":1}
,"massa":{"fusce":1}
,"fusce":{"posuere":1,"est":1}
,"posuere":{"magna":1}
,"magna":{"sed":1,"eros":1}
,"sed":{"pulvinar":1}
,"pulvinar":{"ultricies":1}
,"ultricies":{"purus":1}
,"purus":{"lectus":1,"scelerisque":1}
,"lectus":{"malesuada":1}
,"malesuada":{"libero":1,"fames":1}
,"libero":{"sit":1}
,"commodo":{"magna":1}
,"eros":{"quis":1}
,"quis":{"urna":1}
,"nunc":{"viverra":1,"mauris":1}
,"viverra":{"imperdiet":1}
,"imperdiet":{"enim":1}
,"enim":{"fusce":1}
,"est":{"vivamus":1}
,"vivamus":{"tellus":1}
,"pellentesque":{"habitant":1}
,"habitant":{"morbi":1}
,"morbi":{"tristique":1}
,"tristique":{"senectus":1}
,"senectus":{"netus":1}
,"netus":{"malesuada":1}
,"fames":{"turpis":1}
,"turpis":{"egestas":1}
,"egestas":{"proin":1}
,"proin":{"pharetra":1}
,"pharetra":{"nonummy":1}
,"nonummy":{"pede":1,"augue":1,"broken":1}
,"pede":{"mauris":1}
,"mauris":{"orci":1,"eget":1}
,"aenean":{"nec":1}
,"nec":{"lorem":1}
,"donec":{"laoreet":1}
,"laoreet":{"nonummy":1}
,"suspendisse":{"dui":1}
,"dui":{"purus":1}
,"scelerisque":{"vulputate":1}
,"vulputate":{"vitae":1}
,"vitae":{"pretium":1}
,"pretium":{"mattis":1}
,"mattis":{"nunc":1}
,"eget":{"neque":1}
,"neque":{"sem":1}
,"sem":{"venenatis":1}
,"venenatis":{"eleifend":1}
,"eleifend":{"nonummy":1}
,"broken":{"link":1}
,"link":{"link":1,"points":1}
,"points":{"internal":1,"external":1}
,"internal":{"html":1,"pdf":1}
,"html":{"file":1}
,"file":{"link":1,"(website)":1}
,"pdf":{"file":1}
,"external":{"html":1,"pdf":1}
,"(website)":{"link":1}
}
;Search.control.loadWordPairs(pairs);
